Add unit tests for cn.edu.jxnu.practice
Diffblue-benchmarks/Jxnu-liguobin-cs-summary-reflection pull request #1
Opened 2019-06-11 14:26 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `cn.edu.jxnu.practice` in the `cs-summary-reflection` module is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

2019-06-12 17:17 UTC, petersear requested changes

2019-06-12 17:17 UTC, petersear commented on src/test/java/cn/edu/jxnu/practice/DifferentNumberOfBinaryBits_JavaTest.java
> +public class DifferentNumberOfBinaryBits_JavaTest {
Was there a reason you didn't combine the asserts into one test method?

2019-06-12 17:17 UTC, petersear commented on src/test/java/cn/edu/jxnu/practice/RightShiftTest.java
> +		Assert.assertArrayEquals(new int[]{4, 5, 6, 7, 1, 1, 2, 5, 9}, array);
line > 80 chars

2019-06-12 17:17 UTC, petersear commented on src/test/java/cn/edu/jxnu/practice/RightShiftTest.java
> +		Assert.assertArrayEquals(new int[]{4, 5, 6, 7, 1, 1, 2, 5, 9}, array);
line > 80 chars

2019-06-12 17:17 UTC, petersear commented on src/test/java/cn/edu/jxnu/practice/StringDisplacementTest.java
> +		Assert.assertFalse(StringDisplacement.stringDisplacement2("2", "a/b/c"));
line > 80 chars (and lines following)

2019-06-12 18:27 UTC, paulkennethkent approved these changes

2019-06-13 17:44 UTC, ThomasPerkins1123 commented on src/test/java/cn/edu/jxnu/practice/DifferentNumberOfBinaryBits_JavaTest.java
> +public class DifferentNumberOfBinaryBits_JavaTest {
No real reason I just didn't like only having one test in a class so I didn't merge them together but I have now

2019-06-13 17:56 UTC, petersear approved these changes

2019-09-04 09:30 UTC, merged